#!/bin/sh
#
### BEGIN INIT INFO
# Provides: pf9-ha-slave
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the Platform9 VM HA slave service
### END INIT INFO

# read & export proxy information
. /etc/environment

SHORT_NAME="ha"
svcname="pf9-${SHORT_NAME}"

SERVER_BIN="/opt/pf9/pf9-ha/bin/pf9-ha"

SERVER_OPTS="--config-dir /opt/pf9/etc/pf9-ha/conf.d"

SERVER_LOGFILE=/var/log/pf9/${svcname}-out.log

PIDFILE=/var/run/${svcname}/${svcname}.pid
PYTHON_EGG_CACHE=/tmp/python-eggs

# Source function library.
. /lib/lsb/init-functions


RETVAL=0
uid=`id | cut -d\( -f1 | cut -d= -f2`

start() {

    # Only root can start the service
    [ $uid -ne 0 ] && exit 4

    touch $PIDFILE
    mkdir -p /var/log/pf9
    LD_LIBRARY_PATH="/opt/pf9/python/pf9-lib:/opt/pf9/python/pf9-hostagent-lib:${LD_LIBRARY_PATH}" \
        PYTHONPATH="/opt/pf9/python/lib/python2.7:${PYTHONPATH}" \
        /sbin/start-stop-daemon --start --name $svcname --quiet --pidfile $PIDFILE --exec $SERVER_BIN --chuid pf9 --make-pidfile -- $SERVER_OPTS >> $SERVER_LOGFILE 2>&1 &
    RETVAL=$?
    if [ "$RETVAL" -eq "0" ]; then
        log_success_msg "Started:" "$svcname"
    else
        log_failure_msg "Failed to start:" "$svcname"
    fi
    return $RETVAL
}

stop() {
    servicename=`basename $SERVER_BIN`
    start-stop-daemon --stop  --retry=0/30/KILL/5 --pidfile $PIDFILE --name $servicename
    RETVAL=$?
    if [ "$RETVAL" -eq "0" ]; then
        log_success_msg "Stopped:" "$svcname"
        rm -f $PIDFILE
    else
        log_failure_msg "Failed to stop:" "$svcname"
    fi
    return $RETVAL
}

status() {
    status_of_proc $svcname $svcname
}

# See how we were called.
case "$1" in
    start)
        start
        RETVAL=$?
        ;;
    stop)
        stop
        RETVAL=$?
        ;;
    status)
        status
        RETVAL=$?
        ;;
    restart | reload | force-reload)
        stop
        start
        RETVAL=$?
        ;;
    condrestart | try-restart)
        if status > /dev/null; then
            stop
            start
            RETVAL=$?
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
        RETVAL=2
        ;;
esac

exit $RETVAL
